# Generated by Django 3.2.4 on 2021-06-29 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_cep'),
        ('clientes', '0003_alter_cliente_numero'),
    ]

    operations = [
    ]
